### ISSUE TITLE
Bitcoin Cash tip!

### ISSUE THREAD

**Issue by ghost** [Proteusiq/TrustPilotReader#1]
@GitCash send 0.0005 bch to @Proteusiq

**Comment by ghost** [comment]
@GitCash send 0.0004 bch to @Proteusiq

**Comment by GitCash** [comment]
Hey **Proteusiq**, user **sinbik** tipped you **400 bits** in Bitcoin Cash ( ~ **$0.212** ).

*[Click here to claim it!](https://gitcash.io/claim/Proteusiq)*

You can also add the "thumbs down" reaction to **sinbik**'s comment above to prevent future tips.
